#-------------------------------
# General Site Settings

title: Take the Sword | TTS

# Here you can add link in main menu
menu:
- {name: Work, url: 'work', icon: 'ion ion-ios-briefcase'}
- {name: Blog, url: 'blog', icon: 'ion ion-ios-paper'}
- {name: Contact, url: 'contact', icon: 'ion ion-ios-mail'}

#-------------------------------
# About Section

avatar: 05.jpg
name: Driex
my-job: Not a Jedi, never had a Master.
description: It all started with my co-worker telling me, take the Sword, a reference to PowerShell resolving all issues.
email: noreply@takethesword.nl

#-------------------------------
# Skills Section

skills-title: Professional Skills
skills:
- {name: Exchange, value: '90'}
- {name: Routing/Switching, value: '60'} 
- {name: GreenField Deployments, value: '85'}
- {name: Intune/Azure, value: '70'}
- {name: T-shooting/Building Scripts, value: '80'}
- {name: CyberSecurity, value: '40'}

#-------------------------------
# Experience Section

experience-title: Experience
experience:
- {company-name: Telecom & Projects, duration: 2012 - 2017, job-position: Sys-admin, description: Building greenfield on RedHat Enterprise cluster - New Forest, Multiple DC's, Exchange 2010, Back-up, deployment of RMM tooling Kaseya.}

- {company-name: Telecom & IT, duration: 2017 - 2019, job-position: Project Lead Engineer, description: Setting up migration projects & Building NOC.}

- {company-name: Telecom & IT, duration: 2019 - 2020, job-position: Technical Lead Engineer, description: Expanding NOC.}

- {company-name: Telecom & IT, duration: 2020 - 2021, job-position: Cloud & Security Engineer, description: Building SOC.}

#-------------------------------
# Education Section

education-title: Education
education:
- {degree: Network Administrator, years: 2011 - 2012, organization: University of Grunn, description: Passed.}

- {degree: Servicedesk, years: 2009 - 2010, organization: University of Grunn, description: Passed.}

- {degree: Car Mechanice, years: 2007 - 2008, organization: University of Friesland, description: Passed.}

#-------------------------------
# Clients Section
clients-title: Reviews
clients:
- {
  name: "D Poolie",
  title: "Sys Engineer",
  quote: "<p><strong>Working with Driex was the highlight of my career.</strong> He told me everything & left me QQ.</p>"
}
- {
  name: "Bossman",
  title: "Director of Minions, Telecom & IT",
  quote: "<p><strong>He STRONK.</strong> We gave him trash, he blast past the trash.</p>"
}


#-------------------------------
# Work Section

projects:
- {
  name: Design Talks, 
  image: '10.jpg'
}
- {
  name: Abstract Page, 
  image: '11.jpg'
}
- {
  name: Round Shapes, 
  image: '12.jpg'
}
- {
  name: Color Palette,
  image: '13.jpg'
}
- {
  name: Color Palette,
  image: '14.jpg'
}
- {
  name: Color Palette,
  image: '15.jpg'
}

#-------------------------------
# Social Settings

social:
#- {link: "https://facebook.com", icon: ion-logo-facebook }
- {link: "https://xbox.com", icon: ion-logo-xbox }
- {link: "https://portal.office.com", icon: ion-logo-windows }
- {link: "https://linkedin.com", icon: ion-logo-linkedin }
- {link: "https://github.com", icon: ion-logo-github }
- {link: "https://google.nl", icon: ion-icon-skull }

# social network icons available (https://ionicons.com/): 'xbox' / 'windows' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' /

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------